### ISSUE TITLE
Select SQL database technology for API-Server

### ISSUE THREAD

**Issue by t-lichtenstein** [BPChain/meta#76]
- [x] Select database technology
- [ ] Adapt database to API-Server

**Comment by bisbaldi** [comment]
Mongo
 (-) Mongoose can have difficult to undetstand syntax
 (-) Aggregator Query
 (-) Performance (Logs) ?
 (+) Easy to adapt to new chains/metrics
 (+) Bad written queries are not the DBs fault
 (+) Gather Json Data 

Postgresql 
 (+) Easier to aggregate data ?
 (+) Lots of data, all the same structure --> SQL
 (+) Performance ?
 (-) JSON parsing
 (-) Migration necessary for adding new chains/metrics
 (-) Does it really add value?
 (-) Takes longer than anticipated --> another refactoring sprint blocking feature development
