### ISSUE TITLE
Select Framework for microservice architechture (API-Server)

### ISSUE THREAD

**Issue by t-lichtenstein** [BPChain/meta#78]
- [ ] Should contain ORM for selected SQL dbms

**Comment by bisbaldi** [comment]
Requirements for backend framework:

- easy communication between services (chain collector <—> chain controller <—> frontend handler)
- easy communication with FSOC components
- easy communication with Angular frontend
- database abstraction (ORM)
- structured asynchronous calls/callbacks
- easy dockerizable
